-- MySQL Script generated by MySQL Workbench
-- Tue Mar 24 09:21:46 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `T_PROJECTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_PROJECTS` ;

CREATE TABLE IF NOT EXISTS `T_PROJECTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_LANGUAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_LANGUAGES` ;

CREATE TABLE IF NOT EXISTS `T_LANGUAGES` (
  `id` INT NOT NULL,
  `iso_code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_PROJECT_KEYS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_PROJECT_KEYS` ;

CREATE TABLE IF NOT EXISTS `T_PROJECT_KEYS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `code` VARCHAR(128) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_T_PROJECT_KEYS_T_PROJECTS`
    FOREIGN KEY (`project_id`)
    REFERENCES `T_PROJECTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_T_PROJECT_KEYS_T_PROJECTS_idx` ON `T_PROJECT_KEYS` (`project_id` ASC);

CREATE UNIQUE INDEX `uq_project_key` ON `T_PROJECT_KEYS` (`project_id` ASC, `code` ASC);


-- -----------------------------------------------------
-- Table `T_PROJECT_TRANSLATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_PROJECT_TRANSLATIONS` ;

CREATE TABLE IF NOT EXISTS `T_PROJECT_TRANSLATIONS` (
  `project_key_id` BIGINT NOT NULL,
  `language_id` INT NOT NULL,
  `value` LONGTEXT NULL,
  PRIMARY KEY (`project_key_id`, `language_id`),
  CONSTRAINT `fk_T_PROJECT_TRANSLATIONS_T_PROJECT_KEYS1`
    FOREIGN KEY (`project_key_id`)
    REFERENCES `T_PROJECT_KEYS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_PROJECT_TRANSLATIONS_T_LANGUAGES1`
    FOREIGN KEY (`language_id`)
    REFERENCES `T_LANGUAGES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_T_PROJECT_TRANSLATIONS_T_PROJECT_KEYS1_idx` ON `T_PROJECT_TRANSLATIONS` (`project_key_id` ASC);

CREATE INDEX `fk_T_PROJECT_TRANSLATIONS_T_LANGUAGES1_idx` ON `T_PROJECT_TRANSLATIONS` (`language_id` ASC);


-- -----------------------------------------------------
-- Table `T_PROJECT_SECTIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T_PROJECT_SECTIONS` ;

CREATE TABLE IF NOT EXISTS`T_PROJECT_SECTIONS` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_section_project_idx` (`project_id` ASC),
  CONSTRAINT `fk_T_PROJECT_SECTIONS_T_PROJECTS`
    FOREIGN KEY (`project_id`)
    REFERENCES `T_PROJECTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `T_PROJECT_KEYS` 
ADD COLUMN `project_section_id` BIGINT(20) NULL AFTER `project_id`,
ADD INDEX `fk_T_PROJECT_KEYS_T_PROJECT_SECTIONS_idx` (`project_section_id` ASC);
ALTER TABLE `T_PROJECT_KEYS` 
ADD CONSTRAINT `fk_T_PROJECT_KEYS_T_PROJECT_SECTIONS`
  FOREIGN KEY (`project_section_id`)
  REFERENCES `T_PROJECT_SECTIONS` (`id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
