INSERT INTO `T_LANGUAGES`(`id`, `iso_code`, `name`) VALUES
	(1, 'NL', 'Nederlands'),
    (2, 'FR', 'français'),
	(3, 'EN', 'English'),
    (4, 'DE', 'Deutsch'),
    (5, 'IT', 'italiano'),
	(6, 'ES', 'español'),
    (7, 'BG', 'български'),
    (8, 'CS', 'čeština'),
    (9, 'DA', 'dansk'),
    (11, 'EL', 'ελληνικά'),
    (13, 'ET', 'eesti keel'),
    (14, 'FI', 'suomi'),
    (15, 'HR', 'hrvatski'),
    (16, 'HU', 'magyar'),
    (17, 'LT', 'lietuvių kalba'),
    (18, 'LV', 'latviešu valoda'),
    (19, 'MT', 'Malti'),
    (20, 'PL', 'polski'),
    (21, 'PT', 'português'),
    (22, 'RO', 'română'),
    (23, 'SK', 'slovenčina (slovenský jazyk)'),
    (24, 'SL', 'slovenščina (slovenski jezik)'),
    (25, 'SV', 'svenska');